sudo: false

language: php

php:
  - 7.0

install:
  - composer install

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit

cache:
  directories:
    - vendor

branches:
  only:
    - master
