sudo: false

language: php

php:
  - 7.0

install:
  - composer install

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit

after_success:
  - "curl -H \"Content-Type: application/json\" --data '{\"build\": true}' -X POST ${DOCKER_HUB_TRIGGER}"

cache:
  directories:
    - vendor

branches:
  only:
    - master
