sudo: false

language: php

php:
  - 7.0

install:
  - composer install

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit

after_success:
  - "curl -H \"Content-Type: application/json\" --data '{\"build\": true}' -X POST https://registry.hub.docker.com/u/confhub/backend/trigger/bd32b8db-f1a1-4616-a788-6f97ad1a6df1/"

cache:
  directories:
    - vendor

branches:
  only:
    - master
